### PR TITLE
Added GitHub Action

### PR DESCRIPTION
**Pull request by MarcelCoding**
Added a GitHub action which sorts the `password.csv` and updates the count of passwords in the `README.md` file.

### CODE REVIEW

**Comment by nothing3F** [comment]
Hello, interesting script. It will definitely be useful (especially when there will be several thousand entries to be sorted). Thank you for your contribution!

**Comment by nothing3F** [comment]
Hi, I use the github action you wrote and it sorts passwords in passwords.csv, but it doesn't update the number of passwords in README.md. From what I can see, it should be doing it. Am I doing something wrong that it does not work?

**Comment by MarcelCoding** [comment]
Yesterday it worked. I looked into your readme file, but I can't find any changes. Did you change anything?

**Comment by nothing3F** [comment]
I didn't change anything, and I updated the readme password count manually (because github action wouldn't work).

**Comment by MarcelCoding** [comment]
I found the problem: You changes the count of the code block symbols. [Diff](https://github.com/nothing3F/many-passwords/commit/c09d964ceaba59086b77571bfa029570e7e5246f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1) If you change the count to tow symbols it should work, i tested it local.

**Comment by nothing3F** [comment]
I have uploaded a README from your repository but it still doesn't work. What are ``tow symbols``?

**Comment by nothing3F** [comment]
I understand the mistake. Thank you very much for your help!

**Pull request merged**
