### PR TITLE
HTML Page

### PR DESCRIPTION
**Pull request by alenquer**
HTML page created for viewing on the web.

~ Cheers

### CODE REVIEW

**Comment by nothing3F** [comment]
Hello, an interesting idea is to create a page for this project. Looks good, but I have some questions. Who is the creator of the favicon? It's about copyright. The website works by loading a file from a computer, can the file be loaded automatically from github? I thought about this site before and thought it might be good if it is just a responsive table. What do you think about it? Thanks!

**Comment by alenquer** [comment]
I liked the idea of ​​automatically loading the list from the github repository, and the icon has no copyright, it belongs to **iconmonstr**.
https://iconmonstr.com/about/

**Comment by nothing3F** [comment]
It looks really good. I'm glad there is no problem with copyright. Thank you so much for your contributing!

**Comment by nothing3F** [comment]
[Website](https://nothing3f.github.io/many-passwords/) is working (: The files are in [website tree](https://github.com/nothing3F/many-passwords/tree/website).

**Comment by alenquer** [comment]
Oh! Thank you! I hope it helps people a lot!

**Pull request merged**
