### PR TITLE
Website rework

### PR DESCRIPTION
**Pull request by Mpcs**
Hi, I'm going to modify the website to fit our needs more.
Ignore this PR for now, I'm opening it just so You know someone is working on it.

Current and upcoming features:

- [x] Moved from Flexbox list to Grid Layout
- [x] Made the CSS cleaner
- [x] Change the style and color scheme (I'd want to hear ideas)
- [x] Add a search bar or filtering
- [x] Adding a navigation bar
- [x] Adding About Us page
- [x] Adding a link to the repo
- [x] floating button go to the top

I'm always open for suggestions on stuff You'd like to see or You'd change

### CODE REVIEW

**Comment by nothing3F** [comment]
Hello! I am glad you want to contribute to this project. 

The changes you made look good. I have some suggestions. I think it might be a good idea to adjust the length of the fields containing records from the table so that each single record fits on one line instead of jumping to the next. What do you think? I like this navigation bar and layout used.

On the subject of colors, I will refer to later. 

Good luck, thanks!

**Comment by nothing3F** [comment]
Hi! I have an idea. Maybe it is worth adding the number of collected passwords as it is in the [README](https://github.com/nothing3F/many-passwords/blob/main/README.md) file?

**Comment by fjavierlh** [comment]
Hi! Ups! Sorry, i forgot update the README file. Dont worry, i'll do it in futures PRs ;)

**Comment by nothing3F** [comment]
@fjavierlh fine, but you comment on the wrong PR. 😛

**Comment by fjavierlh** [comment]
Sorry, i'm learning 😅 Thanks for all!

**Comment by Mpcs** [comment]
> 
> 
> Hi! I have an idea. Maybe it is worth adding the number of collected passwords as it is in the [README](https://github.com/nothing3F/many-passwords/blob/main/README.md) file?

That's a good idea!


I have pushed some changes, there's a file called colors.css, you can play around with the color sheme there.
Also I have made a simple search bar, mobile view might not work perfectly right now.

**Comment by nothing3F** [comment]
Hi! I made a few changes, they are all in the [attachment](https://github.com/nothing3F/many-passwords/files/5455015/changes.zip).

I changed the color of comments and removed the shadow. I think the shadow can stay but in a smaller size. I also made changes to the style.css file in ``.model-info p:nth-child(1)``. In script.js, I changed the way comments are displayed.

I really like the look of the site. Dynamic search is very cool. I hope my changes will be helpful, thanks!

**Comment by Mpcs** [comment]
It's ready! Hooray! 😄 I hope it's good now.

**Comment by nothing3F** [comment]
Nice! I'm glad the website is ready. A lot has changed really, you could say it's a completely different page. It looks really good. 

Thank you for your big contribution!

**Pull request merged**
